/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.UserDao;
import javax.swing.JOptionPane;
import model.User;

/**
 *
 * @author do lee
 */
public class DeleteUserView extends javax.swing.JFrame {
    private User user;
    /**
     * Creates new form DeleteUserView
     */
    public DeleteUserView(User user) {
        initComponents();
        this.user=user;
        lb1Message.setText("Bạn có chắc muốn xoá tài khoản: "+ user.getUsername() +" không?" );
                          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1Message = new javax.swing.JLabel();
        btnYes = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb1Message.setText("jLabel1");
        lb1Message.setToolTipText("");

        btnYes.setText("YES");
        btnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYesActionPerformed(evt);
            }
        });

        btnNo.setText("NO");
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(btnYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(btnNo)
                .addGap(62, 62, 62))
            .addComponent(lb1Message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lb1Message)
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNo)
                    .addComponent(btnYes))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYesActionPerformed
        // Xoá tài khoản từ cơ sở dữ liệu
        UserDao userDao = new UserDao();
        boolean isDeleted = userDao.deleteUser(user.getUsername()); // Xoá tài khoản theo username

        // Hiển thị thông báo thành công
        if (isDeleted) {
            // Thông báo thành công
            JOptionPane.showMessageDialog(this, "Xoá tài khoản thành công!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);

            // Sau khi nhấn OK trong hộp thoại, đóng cửa sổ DeleteUserView và quay về trang chủ
            this.dispose(); // Đóng cửa sổ DeleteUserView
            AccountManagementView accountManagementView= new AccountManagementView();
            accountManagementView.setVisible(isDeleted);
        } else {
            JOptionPane.showMessageDialog(this, "Có lỗi xảy ra khi xoá tài khoản.", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnYesActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        this.dispose(); // Đóng cửa sổ DeleteUserView
        FindTheUserView findUserView = new FindTheUserView("delete"); // Mở lại cửa sổ tìm kiếm tài khoản
        findUserView.setVisible(true);
    }//GEN-LAST:event_btnNoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnYes;
    private javax.swing.JLabel lb1Message;
    // End of variables declaration//GEN-END:variables
}
